# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{whoops}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Higginbotham"]
  s.date = %q{2011-08-02}
  s.description = %q{Handles basic notification responsibilities and allows creation of message creation strategies}
  s.email = %q{daniel@flyingmachinestudios.com}
  s.extra_rdoc_files = [
    "README.asciidoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.asciidoc",
    "Rakefile",
    "app/controllers/event_groups_controller.rb",
    "app/controllers/events_controller.rb",
    "app/helpers/event_groups_helper.rb",
    "app/helpers/events_helper.rb",
    "app/helpers/notifications_helper.rb",
    "app/lib/field_names.rb",
    "app/mailers/.gitkeep",
    "app/mailers/whoops/notification_mailer.rb",
    "app/models/whoops/event.rb",
    "app/models/whoops/event_group.rb",
    "app/models/whoops/filter.rb",
    "app/models/whoops/mongoid_search_parser.rb",
    "app/models/whoops/notification_rule.rb",
    "app/views/event_groups/_list.html.haml",
    "app/views/event_groups/index.html.haml",
    "app/views/events/_detail.html.haml",
    "app/views/events/_details.html.haml",
    "app/views/events/index.html.haml",
    "app/views/layouts/whoops.html.haml",
    "config/initializers/date_formats.rb",
    "config/routes.rb",
    "doc/generate.sh",
    "doc/images/dash-filters.png",
    "doc/images/details-search.png",
    "doc/images/highlighter.png",
    "doc/images/icons/README",
    "doc/images/icons/callouts/1.png",
    "doc/images/icons/callouts/10.png",
    "doc/images/icons/callouts/11.png",
    "doc/images/icons/callouts/12.png",
    "doc/images/icons/callouts/13.png",
    "doc/images/icons/callouts/14.png",
    "doc/images/icons/callouts/15.png",
    "doc/images/icons/callouts/2.png",
    "doc/images/icons/callouts/3.png",
    "doc/images/icons/callouts/4.png",
    "doc/images/icons/callouts/5.png",
    "doc/images/icons/callouts/6.png",
    "doc/images/icons/callouts/7.png",
    "doc/images/icons/callouts/8.png",
    "doc/images/icons/callouts/9.png",
    "doc/images/icons/caution.png",
    "doc/images/icons/example.png",
    "doc/images/icons/home.png",
    "doc/images/icons/important.png",
    "doc/images/icons/next.png",
    "doc/images/icons/note.png",
    "doc/images/icons/prev.png",
    "doc/images/icons/tip.png",
    "doc/images/icons/up.png",
    "doc/images/icons/warning.png",
    "doc/images/smallnew.png",
    "doc/images/tiger.png",
    "doc/index.asciidoc",
    "doc/index.html",
    "lib/generators/whoops/assets_generator.rb",
    "lib/generators/whoops/templates/assets/images/_ui/breadcrumb_divider.png",
    "lib/generators/whoops/templates/assets/images/_ui/btn_submit.png",
    "lib/generators/whoops/templates/assets/images/_ui/btn_submit_2.png",
    "lib/generators/whoops/templates/assets/images/_ui/btn_view_site.png",
    "lib/generators/whoops/templates/assets/images/_ui/header_bg.png",
    "lib/generators/whoops/templates/assets/images/_ui/header_shadow.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_add_user.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_alert_error.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_alert_info.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_alert_success.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_alert_warning.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_audio.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_categories.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_edit.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_edit_article.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_folder.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_info.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_jump_back.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_logout.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_new_article.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_photo.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_profile.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_search.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_security.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_settings.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_tags.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_trash.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_user.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_video.png",
    "lib/generators/whoops/templates/assets/images/_ui/icn_view_users.png",
    "lib/generators/whoops/templates/assets/images/_ui/module_footer_bg.png",
    "lib/generators/whoops/templates/assets/images/_ui/post_message.png",
    "lib/generators/whoops/templates/assets/images/_ui/secondary_bar.png",
    "lib/generators/whoops/templates/assets/images/_ui/secondary_bar_shadow.png",
    "lib/generators/whoops/templates/assets/images/_ui/sidebar.png",
    "lib/generators/whoops/templates/assets/images/_ui/sidebar_divider.png",
    "lib/generators/whoops/templates/assets/images/_ui/sidebar_shadow.png",
    "lib/generators/whoops/templates/assets/images/_ui/table_sorter_header.png",
    "lib/generators/whoops/templates/assets/javascripts/hideshow.js",
    "lib/generators/whoops/templates/assets/javascripts/jquery-1.5.2.min.js",
    "lib/generators/whoops/templates/assets/javascripts/jquery.equalHeight.js",
    "lib/generators/whoops/templates/assets/javascripts/jquery.form.js",
    "lib/generators/whoops/templates/assets/javascripts/jquery.tablesorter.min.js",
    "lib/generators/whoops/templates/assets/javascripts/ui.js",
    "lib/generators/whoops/templates/assets/javascripts/whoops.js",
    "lib/generators/whoops/templates/assets/stylesheets/ie.css",
    "lib/generators/whoops/templates/assets/stylesheets/sass/_base.scss",
    "lib/generators/whoops/templates/assets/stylesheets/sass/ie.scss",
    "lib/generators/whoops/templates/assets/stylesheets/sass/screen.scss",
    "lib/generators/whoops/templates/assets/stylesheets/screen.css",
    "lib/whoops.rb",
    "lib/whoops/engine.rb",
    "spec/controllers/event_groups_controller_spec.rb",
    "spec/dummy/Rakefile",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/mongoid.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/public/images/_ui/breadcrumb_divider.png",
    "spec/dummy/public/images/_ui/btn_submit.png",
    "spec/dummy/public/images/_ui/btn_submit_2.png",
    "spec/dummy/public/images/_ui/btn_view_site.png",
    "spec/dummy/public/images/_ui/header_bg.png",
    "spec/dummy/public/images/_ui/header_shadow.png",
    "spec/dummy/public/images/_ui/icn_add_user.png",
    "spec/dummy/public/images/_ui/icn_alert_error.png",
    "spec/dummy/public/images/_ui/icn_alert_info.png",
    "spec/dummy/public/images/_ui/icn_alert_success.png",
    "spec/dummy/public/images/_ui/icn_alert_warning.png",
    "spec/dummy/public/images/_ui/icn_audio.png",
    "spec/dummy/public/images/_ui/icn_categories.png",
    "spec/dummy/public/images/_ui/icn_edit.png",
    "spec/dummy/public/images/_ui/icn_edit_article.png",
    "spec/dummy/public/images/_ui/icn_folder.png",
    "spec/dummy/public/images/_ui/icn_info.png",
    "spec/dummy/public/images/_ui/icn_jump_back.png",
    "spec/dummy/public/images/_ui/icn_logout.png",
    "spec/dummy/public/images/_ui/icn_new_article.png",
    "spec/dummy/public/images/_ui/icn_photo.png",
    "spec/dummy/public/images/_ui/icn_profile.png",
    "spec/dummy/public/images/_ui/icn_search.png",
    "spec/dummy/public/images/_ui/icn_security.png",
    "spec/dummy/public/images/_ui/icn_settings.png",
    "spec/dummy/public/images/_ui/icn_tags.png",
    "spec/dummy/public/images/_ui/icn_trash.png",
    "spec/dummy/public/images/_ui/icn_user.png",
    "spec/dummy/public/images/_ui/icn_video.png",
    "spec/dummy/public/images/_ui/icn_view_users.png",
    "spec/dummy/public/images/_ui/module_footer_bg.png",
    "spec/dummy/public/images/_ui/post_message.png",
    "spec/dummy/public/images/_ui/secondary_bar.png",
    "spec/dummy/public/images/_ui/secondary_bar_shadow.png",
    "spec/dummy/public/images/_ui/sidebar.png",
    "spec/dummy/public/images/_ui/sidebar_divider.png",
    "spec/dummy/public/images/_ui/sidebar_shadow.png",
    "spec/dummy/public/images/_ui/table_sorter_header.png",
    "spec/dummy/public/javascripts/hideshow.js",
    "spec/dummy/public/javascripts/jquery-1.5.2.min.js",
    "spec/dummy/public/javascripts/jquery.equalHeight.js",
    "spec/dummy/public/javascripts/jquery.form.js",
    "spec/dummy/public/javascripts/jquery.tablesorter.min.js",
    "spec/dummy/public/javascripts/rails.js",
    "spec/dummy/public/javascripts/ui.js",
    "spec/dummy/public/javascripts/whoops.js",
    "spec/dummy/public/stylesheets/.gitkeep",
    "spec/dummy/public/stylesheets/ie.css",
    "spec/dummy/public/stylesheets/sass/_base.scss",
    "spec/dummy/public/stylesheets/sass/ie.scss",
    "spec/dummy/public/stylesheets/sass/screen.scss",
    "spec/dummy/public/stylesheets/screen.css",
    "spec/dummy/script/rails",
    "spec/fabricators/whoops_event_group_fabricator.rb",
    "spec/fabricators/whoops_filter_fabricator.rb",
    "spec/helpers/event_groups_helper_spec.rb",
    "spec/helpers/events_helper_spec.rb",
    "spec/integration/navigation_spec.rb",
    "spec/models/whoops/event_group_spec.rb",
    "spec/models/whoops/event_spec.rb",
    "spec/models/whoops/filter_spec.rb",
    "spec/models/whoops/mongoid_search_parser_spec.rb",
    "spec/models/whoops/notification_rule_spec.rb",
    "spec/spec_helper.rb",
    "spec/whoops_spec.rb",
    "whoops.gemspec"
  ]
  s.homepage = %q{http://www.whoopsapp.com}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{The Whoops engine stores logs and provides an interface to view them.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<whoops>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, ["= 0.8.7"])
      s.add_runtime_dependency(%q<rails>, ["~> 3"])
      s.add_runtime_dependency(%q<sass>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<mongo>, [">= 0"])
      s.add_runtime_dependency(%q<bson_ext>, [">= 0"])
      s.add_runtime_dependency(%q<mongoid>, ["= 2.0.1"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<fabrication>, [">= 0"])
      s.add_development_dependency(%q<faker>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0.4.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
    else
      s.add_dependency(%q<whoops>, [">= 0"])
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<rails>, ["~> 3"])
      s.add_dependency(%q<sass>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<mongo>, [">= 0"])
      s.add_dependency(%q<bson_ext>, [">= 0"])
      s.add_dependency(%q<mongoid>, ["= 2.0.1"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<fabrication>, [">= 0"])
      s.add_dependency(%q<faker>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0.4.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
    end
  else
    s.add_dependency(%q<whoops>, [">= 0"])
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<rails>, ["~> 3"])
    s.add_dependency(%q<sass>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<mongo>, [">= 0"])
    s.add_dependency(%q<bson_ext>, [">= 0"])
    s.add_dependency(%q<mongoid>, ["= 2.0.1"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<fabrication>, [">= 0"])
    s.add_dependency(%q<faker>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0.4.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
  end
end

